### PR TITLE
Add macros many0_count! and many1_count!

### PR DESCRIPTION
**Pull request by tsraom**
Continued from #819.
This is associated with issue #818.

### CODE REVIEW

**Comment by tsraom** [comment]
I messed up the other branch so I made a new one. Looks like it works fine with the current master! @Geal

**Comment by Geal** [comment]
hello! could you add some unit tests for those combinators?

**Comment by tsraom** [comment]
Where should I add them? Under [`nom/tests`](https://github.com/tsraom/nom/tree/tsraom-many-again/tests)?

**Comment by Geal** [comment]
they can be in multi.rs at the end of the file

**Comment by tsraom** [comment]
I have added the tests and merged with the current master. Since current master fails to build because of errors unrelated to this PR, this branch fails to build on this commit as well.

**Comment by Geal** [comment]
I'm fixing the build failure. In the meantime, could you rebase above master instead of merging it?

**Comment by Geal** [comment]
I rebased the PR and integrated it as 001d7bf, thank you for the new feature!

**Comment by tsraom** [comment]
Sorry for the lack of response over the past couple of days, and thanks for the integration! :)

**Pull request closed without merging**
