### PR TITLE
Remove bitvec from default features

### PR DESCRIPTION
**Pull request by djc**
As discussed in #1287. That said, the approach suggested in #1323 would probably make more sense in the end.

### CODE REVIEW

**Comment by Geal** [comment]
LGTM. Maybe bitvec-alloc could require alloc? (and bitvec-std require std)

**Comment by djc** [comment]
Should we first discuss in #1323 whether the bitvec parsers will remain part of the main crate? If so, this PR doesn't make sense.

**Comment by Geal** [comment]
it makes sense in that I can push a 7.0.0-alpha with that fix right now, which would unlock the tarpaulin issue, and then we can see how to move bitvec in a separate crate for the real release (yes this is kinda cheating with semver)

**Comment by djc** [comment]
Done.

**Comment by Geal** [comment]
thanks

**Comment by Geal** [comment]
@djc https://crates.io/crates/nom/7.0.0-alpha1 (it also includes bitvec upgrades for now)

**Pull request merged**
