### PR TITLE
Add doc and comment for count_fixed! output being Copy

### PR DESCRIPTION
**Pull request by bluss**

### CODE REVIEW

**Comment by bluss** [comment]
Not sure if this is needed. Just looking at all `unsafe` blocks. The output type being `Copy` guards this code from having panic / exception safety issues (destructors would run on uninit data at panic otherwise).

**Comment by bluss** [comment]
(Since submac is user supplied, we can insert a panic while the uninit array is alive.)

**Comment by Geal** [comment]
I see, nice catch! If you have other ideas like this one, I'm all ears :)

**Comment by bluss** [comment]
I'm just auditing the `unsafe` code in the crate, hope you don't mind. The other important issue is the `print_offsets` (and similar functions) one.

To clarify this issue, The `[T; N]` expression is what imposes the `T: Copy` bound. Which is fortunate, without that bound, the code wouldn't be panic safe. Putting in the comment is good to ensure this isn't lost in refactoring.

**Comment by bluss** [comment]
I think you'll be in a great position with these fixed. Not only offering safe rust-based parsing with very high performance, but doing so using almost no `unsafe`-marked code.

**Pull request merged**
