### PR TITLE
[wip] Add example to `one_of`

### PR DESCRIPTION
**Pull request by derekdreery**

### CODE REVIEW

**Comment by derekdreery** [comment]
I'll add the str support to this PR, so closing #429

**Comment by derekdreery** [comment]
Having looked at this some more, it seems sensible to break backwards compatibility, to make the signature like `is_not!`, @Geal do you think this is the correct way to do this?

**Comment by Geal** [comment]
why would it break backward compatibility?

**Comment by derekdreery** [comment]
hmm I didn't understand how general the new-style is, I'm still trying to understand what the macro will take and produce.

**Comment by Geal** [comment]
could you try again, now that I pushed 59ef6901d012be8d804490 ?

**Comment by Geal** [comment]
Thanks!

**Pull request merged**
