### PR TITLE
delimited test overhaul

### PR DESCRIPTION
**Pull request by tstorch**
More complete delimited test

### CODE REVIEW

**Comment by Geal** [comment]
It looks like `delimited` does not count data correctly when it's incomplete.

For `ab` it should give `Incomplete(Needed::Size(3))` (correct), for `abcde` it should give `Incomplete(Needed::Size(6))` (correct), for `abcdefgh` it should give `Incomplete(Needed::Size(9))` (correct). Can you update the test to reflect that? I'll fix `delimited` to match those tests.

**Comment by tstorch** [comment]
Done with a rebase

**Comment by tstorch** [comment]
Your idea seems reasonable.

I'm not that proficient in macros, but could you use `tuple` to implement `preceded`, `terminated` and `delimited`, i.e. "`preceded!(a, b)` = `tuple!(a, b).1`" and "`terminated!(a, b)` = `tuple!(a, b).0`"? Or could you use `preceded` and `terminated` to implement `delimited` a la `delimited!(a, b, c)` = `preceded!(a, terminated!(b, c))` = `terminated!(preceded!(a, b), c)`?

**Comment by Geal** [comment]
Yes, they could be done either way. It is easy to match on the result of `tuple` and select the needed output. I'll implement that when I get the time

**Comment by Geal** [comment]
I'm currently updating code to use tuple everywhere, so I'm merging all those PRs

**Comment by tstorch** [comment]
Nice!

**Pull request merged**
