### PR TITLE
Add fold_many combinators

### PR DESCRIPTION
**Pull request by panicbit**
`fold_many0!`, `fold_many1!` and `fold_many_m_n!` are similar to their `many*` pendants, but add two additional parameters (an initial value and a function) to allow folding into a custom type, like you can with Iterator::fold.

### CODE REVIEW

**Comment by panicbit** [comment]
#185 has relevant changes that I want to integrate into the `fold_*` macros. Do not merge yet.

**Comment by Geal** [comment]
This looks useful! I'll make a pass on other pull requests like #185 then we'll see to merge this one

**Comment by tstorch** [comment]
@panicbit This seems pretty useful, but be sure to look at #185 as it is a overhaul of the `many0!` macro, which seems to be the base for yours

**Comment by panicbit** [comment]
I rebased onto #185 now.

**Comment by rundrop1** [comment]
+1 Definitely want this. Great work!

**Comment by Geal** [comment]
Thanks!

**Pull request merged**
