### PR TITLE
Updated tag and test macro and test overhaul

### PR DESCRIPTION
**Pull request by tstorch**
Becaus I f*cked up my git tree a little bit, I need to open this as a new PR. This is basically what was ment to be in #180 

Now the tag and take macros in the test in `macros.rs` are those from `bytes.rs` (copied). To get a better test coverage the test in `macros.rs` got a treatment. I spared some, because they might fail after an overhaul of the according macros.

Someone needs to refactor the macros to ditch circular inclusions, resp. copying code. I will make a proposal for this in the near future via a PR.

Based upon this commit I will rewrite the separeted_list and many0 macros.

### CODE REVIEW

**Comment by tstorch** [comment]
I'm not quite sure, why you return `Incomplete(Needed::Unknown)` in and not `Incomplete(Needed::Size(n))` in the pair macro for the current enclosed parsing macro, like in every other macro. Could you clarify this?

**Comment by tstorch** [comment]
Sorry. I did mean `counter` and `counter_fixed` macros returning `Incomplete(Needed::Unknown)` instead of `Incomplete(Needed::Size(n))`...

**Comment by Geal** [comment]
You really should separate your fixes in smaller pull requests. Fixing the `tag!` implementation in tests is fine, but rewriting all the tests in the same PR is not. From a quick look, I can see a lot of them are improved, but this is a lot of code to review at once. If you want to help me merge things quickly, please make smaller changes.

**Comment by tstorch** [comment]
Got it! Will do it tomorrow...

**Comment by tstorch** [comment]
I reverted the last commit. Now this only includes the updated tag macro and the test that needed to be adapted for this the succeed. The reverted stuff will be split up and I will open separat PRs for each

**Comment by Geal** [comment]
Could you squash the "test overhaul" commit and its revert?

**Comment by tstorch** [comment]
I made a `reset tag-take-tests-overhaul^^` and force pushed it, because the last two commits together did nothing (it would have been a empty commit).

**Comment by tstorch** [comment]
All the substantial parts of the reverted/removed commit(s) have been split up and are now part of the PRs #194, #195, #196, #197, #198, #199, #200, #201, #202, #203, #204, #205, #206, #207, #208, #209, #210, #211

**Comment by Geal** [comment]
Thanks for putting up with my demands!

We will get through all these pull requests ;)

**Pull request merged**
