### PR TITLE
Update lexical-core version to "^0.6".

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Patches:
- #1100
- #1080
- #1066
- And a few upstream issues.

### CODE REVIEW

**Comment by Razican** [comment]
Now that 0.7 has been released, it would be a nice addition to this :)

**Comment by Alexhuszagh** [comment]
@Razican, eventually, yes, however, v0.7 only has support for Rustc >= 1.37, while v0.6 has support for Rustc >= 1.24 (this is due to dependency restrictions). I would like to avoid any breaking changes in Nom currently, but ideally yes, long-term, that would be ideal :D.

**Comment by ErichDonGubler** [comment]
Looks like upgrading to 0.7 is just a bump -- tests still pass. :smile:

**Comment by Geal** [comment]
thank you for this! I'll probably raise the minimum Rust version for nom 6, so it could switch to v0.7

**Pull request merged**
