### PR TITLE
Ported all regular expression macros to functions

### LINKED ISSUE #978: Regex parsers to be ported from macros to functions
Per the 5.0 release, one of the [goals was to port macros over to functions](https://github.com/Geal/nom/issues/878).

The regex parsers have not yet gotten ported. 

I am sorry that I do not have a good test case for this, but the current test suite for regex-based parsers [still use the macro versions](https://github.com/Geal/nom/blob/5.0.0/src/regexp.rs#L663-L685):

```
  #[cfg(feature = "alloc")]
  #[test]
  fn re_capture() {
    named!(rm< &str,Vec<&str> >, re_capture!(r"([[:alpha:]]+)\s+((\d+).(\d+).(\d+))"));
    assert_eq!(
      rm("blah nom 0.3.11pouet"),
      Ok(("pouet", vec!["nom 0.3.11", "nom", "0.3.11", "0", "3", "11"]))
    );
    assert_eq!(
      rm("blah"),
      Err(Err::Error(error_position!(
        &"blah"[..],
        ErrorKind::RegexpCapture
      )))
    );
    assert_eq!(
      rm("hello nom 0.3.11 world regex 0.1.41"),
      Ok((
        " world regex 0.1.41",
        vec!["nom 0.3.11", "nom", "0.3.11", "0", "3", "11"]
      ))
    );
  }
```

### PR DESCRIPTION
**Pull request by loewenheim**
This adds functions versions for all `re_*` macros except the `*_static` ones, as they can't be trivially converted into functions. All the old macros still exist, they just call the function versions now.

Fixes #978.

### CODE REVIEW

**Comment by Lucretiel** [comment]
Personally, I'd argue in favor of the new functions accepting `Regex` objects, rather than `&str`. That gives the user the flexibility to construct their own (for instance, with a `RegexBuilder` if they need)

**Comment by loewenheim** [comment]
I think you’re right. I suppose that means that the macros should keep their current signatures, right?

**Comment by loewenheim** [comment]
Two things I realized:

1. It would probably make sense to organize the functions into modules `regexp::string` and `regexp::bytes` so that we don‘t need function names `re_match`, `re_bytes_match`, etc. (And maybe rename `regexp` to `regex` while we’re at it? “`regexp`” is kind of nonstandard.)
2. Should the parser combinators borrow the `Regex` or take ownership? I initially tended towards borrowing, but I think owning them would make the design a lot simpler.

**Comment by Lucretiel** [comment]
2: I'm in favor of ownership, mostly because it makes the story with closures and "return impl Fn" much cleaner. I'm struggling to think of a use case where you'd NEED a borrow, because I'd expect that the regular expressions used in a constructed nom parser don't also need to be used outside of it.

**Comment by Lucretiel** [comment]
The only thing I can think of is if you have two separate combinators that use the same regular expression, but even then I'd expect that it can be abstracted such that the regular expression is used in a single parse method that is reused in the different methods that need it

**Comment by loewenheim** [comment]
The main case for references are the currently existing `re_foo_static!` macros. They lazily create a static regex and take it by reference. I don’t see how that could be done without the functions working by reference—there’s nothing to take ownership of.

In any case, the current version works with both! Someone helpfully explained the `Borrow` trait to me on reddit and it seems to do exactly what I need.

**Comment by Geal** [comment]
I don't think the borrows are needed either, and that additional trait bound is puzzling. Having the parser own the regex is fine. Could you update the PR for this? Sorry I was not able to check it sooner

**Comment by loewenheim** [comment]
What should I do about the `*_static` macros in that case?

**Comment by Lucretiel** [comment]
Honestly, I'd just omit them for now, until someone has a strong use case for one. It seems like owned version is always preferable, since you can freely reuse the parser without paying the cost for constructing the regex, and you avoid the complexity and branch cost of using a lazy_static

**Comment by Geal** [comment]
Thank you for taking care of this module! I think too it's better to remove the static version for now

**Pull request merged**
