### PR TITLE
Port bit parsers to v5

### PR DESCRIPTION
**Pull request by proman21**
Addresses #892 .

As the bits parsers are the only parsers that change the input type, previously inferred types now have to be explicitly named. This mostly affects tests and benchmarks in the crate; most users of the crate will likely explicitly type the input, which aids inference.

`bits/mod.rd` includes `impl ParseError<I> for ((I, usize), ErrorKind)` and `impl ParseError<(I, usize)> for (I, ErrorKind)` in order to satisfy trait bounds on combinators.

### CODE REVIEW

**Comment by Geal** [comment]
Hello, could you rebase your PR? It's a bit hard to review in that state

**Comment by Geal** [comment]
It looks like something is still wrong with the rebase (looking at the commits). could you check?

**Comment by proman21** [comment]
Ah thanks! I've managed to fix the history up.

**Comment by Geal** [comment]
why do you get type inference issues in 1025aa1d0787a27af60 ? Which Rust version are you using? Ideally there should only be e64f3ca7ca38 in the PR, the rest is unrelated

**Comment by Geal** [comment]
the CI indicates a test is failing: https://travis-ci.org/Geal/nom/jobs/546233532#L1285

**Comment by Geal** [comment]
I'll try to review the entire code this afternoon

**Comment by proman21** [comment]
> why do you get type inference issues in [1025aa1](https://github.com/Geal/nom/commit/1025aa1d0787a27af60e22142c2a236931dcf25d) ? Which Rust version are you using? Ideally there should only be [e64f3ca](https://github.com/Geal/nom/commit/e64f3ca7ca38078d60a0e99056fc59c0b3e49a39) in the PR, the rest is unrelated

I'm on 1.35.0, and this is error I get when running `cargo test`.
nom bits type inference

The compiler is unable to infer between `ParseError<I>` and `ParseError<(I, usize)>` for
`(I, ErrorKind)`, so you have to specify the full type of `E` in `IResult<I, O, E>`.

> the CI indicates a test is failing: https://travis-ci.org/Geal/nom/jobs/546233532#L1285

I'll need to port over the code from `bits.rs:124-127` that does a checked mul.

**Comment by proman21** [comment]
I didn't get an error for the `issue_848_overflow_incomplete_bits_to_bytes` test when I ran `cargo test` because it requires the `regexp` feature, which I think might be an incorrect configuration. Just an FYI.

**Comment by Geal** [comment]
ok, I think I know where the issue comes from. If we only take e64f3ca and apply this (ignoring the errors with `crate::` import):
```diff
diff --git a/src/bits/macros.rs b/src/bits/macros.rs
index eeadbe5..d8c30c4 100755
--- a/src/bits/macros.rs
+++ b/src/bits/macros.rs
@@ -169,7 +169,7 @@ mod tests {
     assert_eq!(ch((&sl[..1], 0)), Err(Err::Incomplete(Needed::Size(5))));
   }
 
-  fn ch_bytes(input: &[u8]) -> IResult<&[u8], (u8, u8), ((&[u8], usize), ErrorKind)> {
+  fn ch_bytes(input: &[u8]) -> IResult<&[u8], (u8, u8), (&[u8], ErrorKind)> {
     bits!(input, ch)
   }
 
@@ -219,7 +219,7 @@ mod tests {
     }
   }
 
-  fn take_uint(input: (&[u8], usize), take: usize) -> IResult<(&[u8], usize), FakeUint, (&[u8], ErrorKind)> {
+  fn take_uint(input: (&[u8], usize), take: usize) -> IResult<(&[u8], usize), FakeUint, ((&[u8], usize), ErrorKind)> {
     take_bits!(input, take)
   }
 
diff --git a/src/bits/mod.rs b/src/bits/mod.rs
index d6935dd..ae5a815 100755
--- a/src/bits/mod.rs
+++ b/src/bits/mod.rs
@@ -62,6 +62,7 @@ where
   }
 }
 
+/*
 impl<I> ParseError<(I, usize)> for (I, ErrorKind) {
   fn from_error_kind((input, _): (I, usize), kind: ErrorKind) -> (I, ErrorKind) {
     (input, kind)
@@ -81,6 +82,7 @@ impl<I> ParseError<I> for ((I, usize), ErrorKind) {
     other
   }
 }
+*/
 
 /// Converts a byte-level input to a bit-level input, for consumption by a parser that uses bits.
 ///
@@ -103,10 +105,10 @@ impl<I> ParseError<I> for ((I, usize), ErrorKind) {
 ///
 /// assert_eq!(take_4_bits( sl ), Ok( (&sl[1..], 0xA) ));
 /// ```
-pub fn bits<I, O, E: ParseError<(I, usize)>, P>(parser: P) -> impl Fn(I) -> IResult<I, O, E>
+pub fn bits<I, O, E1: ParseError<(I, usize)>+Into<E2>, E2: ParseError<I>, P>(parser: P) -> impl Fn(I) -> IResult<I, O, E2>
 where
   I: InputIter<Item = u8> + Slice<RangeFrom<usize>>,
-  P: Fn((I, usize)) -> IResult<(I, usize), O, E>,
+  P: Fn((I, usize)) -> IResult<(I, usize), O, E1>,
 {
   move |input: I| match parser((input, 0)) {
     Ok(((rest, offset), res)) => {
@@ -114,16 +116,16 @@ where
       Ok((rest.slice(byte_index..), res))
     }
     Err(Err::Incomplete(n)) => Err(Err::Incomplete(n.map(|u| u / 8 + 1))),
-    Err(Err::Error(e)) => Err(Err::Error(e)),
-    Err(Err::Failure(e)) => Err(Err::Failure(e)),
+    Err(Err::Error(e)) => Err(Err::Error(e.into())),
+    Err(Err::Failure(e)) => Err(Err::Failure(e.into())),
   }
 }
 
 #[doc(hidden)]
-pub fn bitsc<I, O, E: ParseError<(I, usize)>, P>(input: I, parser: P) -> IResult<I, O, E>
+pub fn bitsc<I, O, E1: ParseError<(I, usize)>+Into<E2>, E2: ParseError<I>, P>(input: I, parser: P) -> IResult<I, O, E2>
 where
   I: InputIter<Item = u8> + Slice<RangeFrom<usize>>,
-  P: Fn((I, usize)) -> IResult<(I, usize), O, E>,
+  P: Fn((I, usize)) -> IResult<(I, usize), O, E1>,
 {
   bits(parser)(input)
 }
@@ -153,10 +155,10 @@ where
 ///
 /// assert_eq!(parse( input ), Ok(( &[][..], (0xd, 0xea, &[0xbe, 0xaf][..]) )));
 /// ```
-pub fn bytes<I, O, E: ParseError<I>, P>(parser: P) -> impl Fn((I, usize)) -> IResult<(I, usize), O, E>
+pub fn bytes<I, O, E1: ParseError<I>+Into<E2>, E2: ParseError<(I, usize)>, P>(parser: P) -> impl Fn((I, usize)) -> IResult<(I, usize), O, E2>
 where
   I: InputIter<Item = u8> + Slice<RangeFrom<usize>>,
-  P: Fn(I) -> IResult<I, O, E>,
+  P: Fn(I) -> IResult<I, O, E1>,
 {
   move |(input, offset): (I, usize)| {
     let inner = if offset % 8 != 0 {
@@ -164,16 +166,20 @@ where
     } else {
       input.slice((offset / 8)..)
     };
-    let (rest, res) = parser(inner)?;
-    Ok(((rest, 0), res))
+    match parser(inner) {
+      Ok((rest, res)) => Ok(((rest, 0), res)),
+      Err(Err::Incomplete(n)) => Err(Err::Incomplete(n.map(|u| u * 8))),
+      Err(Err::Error(e)) => Err(Err::Error(e.into())),
+      Err(Err::Failure(e)) => Err(Err::Failure(e.into())),
+    }
   }
 }
 
 #[doc(hidden)]
-pub fn bytesc<I, O, E: ParseError<I>, P>(input: (I, usize), parser: P) -> IResult<(I, usize), O, E>
+pub fn bytesc<I, O, E1: ParseError<I>+Into<E2>, E2: ParseError<(I, usize)>, P>(input: (I, usize), parser: P) -> IResult<(I, usize), O, E2>
 where
   I: InputIter<Item = u8> + Slice<RangeFrom<usize>>,
-  P: Fn(I) -> IResult<I, O, E>,
+  P: Fn(I) -> IResult<I, O, E1>,
 {
   bytes(parser)(input)
 }
```

From what I understand, you inverted the way errors were returned. `bits!` generates a parser that takes a `I` as input and returns a `IResult<I, T, E>` with `E: ParseError<I>`: https://github.com/Geal/nom/blob/master/src/bits.rs#L19
while the new `bits` function returns a `IResult<I, T, E>` with `E: ParseError<(I, usize)>`: https://github.com/Geal/nom/pull/957/commits/e64f3ca7ca38078d60a0e99056fc59c0b3e49a39#diff-c182431a163705ad034394497e21d004R106

If you take the modifications I show on `bits`, `bitsc`, `bytes` and `bytesc`, you can avoid the `ParseError` modifications, and revert all the changes made to the tests.
As an example, the `bits_to_bytes` test previously had a `ch_bytes` with `(&[u8], ErrorKind)` as error type: https://github.com/Geal/nom/blob/master/src/bits.rs#L324-L327

**Comment by proman21** [comment]
So I took this route initially when I first encountered the `ParseError` trait bound problem. The issue is that for the default error type `(I, ErrorKind)`, any non-local trait implementation on the `I` generic type will not compile due to [orphan rules](https://doc.rust-lang.org/error-index.html#E0210).

```rust
// This will fail to compile.
impl<I> From<((I, usize), ErrorKind)> for (I, ErrorKind) { .. }
```

That's why I had to use the `ParseError` trait to create the necessary polymorphism.

If you're amenable to it, we can still use a `From` style impl by creating a newtype for `(I, ErrorKind)`, maybe something like this.
```rust
pub struct NomError<I>((I, ErrorKind));
```
This solves the orphan rules problem, and is recommended in that error message.

**Comment by Geal** [comment]
why would there be an issue with orphan rules from within nom's code?

**Comment by Geal** [comment]
oh, right, I see what you mean. I'll test some things and see if I can fix this

**Comment by Geal** [comment]
I've rewritten from scratch in c71ddc6, 51ce76a, 0313c1d and 1aeea19, it was easier than going through all the tests that were modified.
Instead of using a `From` implementation that suffers from the orphan rules, there's an internal trait for error conversion. This is not the prettiest solution, but it minimizes the impact of the change.
Thank you so much for your help!

**Pull request closed without merging**
