### PR TITLE
Fix warnings in return_error!().

### PR DESCRIPTION
**Pull request by ProgVal**

### CODE REVIEW

**Comment by Geal** [comment]
Hello,
unfortunately, the `unify_types` function is there to trick the compiler's type inference into guessing the right types, so it should stay

**Comment by ProgVal** [comment]
Could we use `#[allow(unused)]`?

**Comment by ProgVal** [comment]
Er, no, I don't think does anything to the compiler if it is not called

**Comment by Geal** [comment]
I just took a look, the `unify_types` trick is not used in that pattern, so it's fine to merge, sorry for the delay

**Pull request merged**
