### PR TITLE
terminated test overhaul

### PR DESCRIPTION
**Pull request by tstorch**
More complete terminated test

This test will succeed once #184 is merged

### CODE REVIEW

**Comment by Geal** [comment]
same as `delimited`, `terminated` does not calculate offsets correctly. I think implementing combinators like `delimited` or `terminated` using `tuple` instead of their own code would solve everything easily.

**Comment by Geal** [comment]
Can you update the tests to expect `Incomplete(Needed::Size(8))` for `abcde`?

**Comment by tstorch** [comment]
Done with a rebase

**Comment by Geal** [comment]
Thanks

**Pull request merged**
