### PR TITLE
Add `alt_complete!` convenience combinator

### PR DESCRIPTION
**Pull request by dirk**
Follow-up to #132.

### CODE REVIEW

**Comment by dirk** [comment]
@Geal: Friendly ping about this. :smile:

**Comment by Geal** [comment]
Nice :)

Just a nitpick, could you use `_` to match `$crate::IResult::Incomplete(_) | $crate::IResult::Error(_)` ? This will make the code a little bit easier to read.

**Comment by dirk** [comment]
@Geal: Oh, nice catch; fixed!

**Comment by Geal** [comment]
Thanks!

**Pull request merged**
