### PR TITLE
Added documentation for nom 5.0 bytes/mods.rs

### PR DESCRIPTION
**Pull request by Waelwindows**
This pull request ticks the bytes section of #915. Please tell me if there's anything that needs changing/fixing

### CODE REVIEW

**Comment by Waelwindows** [comment]
The build fails due to the other files that we're not changed in the pull request...

**Comment by Geal** [comment]
could you rebase this PR? Now the combinators in `bytes` are split in `bytes::complete` and `bytes::streaming`, so that commit would not apply to master

**Comment by Waelwindows** [comment]
As the 5.0 branch still doesn't have `bytes` split I'll close this issue, and open a different pull request

**Comment by Geal** [comment]
The development of 5.0 happens in master now

**Pull request closed without merging**
