### PR TITLE
Add pub(crate) support

### PR DESCRIPTION
**Pull request by derekdreery**
Adds pub(crate) support where pub support is present in `macros.rs`.

### CODE REVIEW

**Comment by derekdreery** [comment]
Currently there are no extra tests - I'll  see if I can add some.

**Comment by Geal** [comment]
hi! apparently the test cannot compile on current stable. IIRC that feature is still experimental, right?

**Comment by derekdreery** [comment]
Aah I thought it was already stable. You are correct. Can I mark this PR as blocked by upstream until the syntax becomes stable?

**Comment by derekdreery** [comment]
I've tested and it works on beta - not stable.. I think it was stabilized in 1.19, but maybe there are some changes in macros to support it in 1.20. Anyway, all tests pass in 1.20, so when that's released this should be mergeable.

**Comment by derekdreery** [comment]
1.20 has been released now, so this should work

**Comment by derekdreery** [comment]
Version 1.20 is out, so this should no longer be blocked. I need to trigger a ci reload.

**Comment by derekdreery** [comment]
I think there's an unstable 'vis' identifier, that would make all these variants unnecessary

**Comment by CAD97** [comment]
[Tracking issue for `:vis` macro matcher](https://github.com/rust-lang/rust/issues/41022)

Seems to be almost en route to stabilization.

**Comment by Geal** [comment]
Thank you! This is getting in nom at last :)

**Comment by derekdreery** [comment]
Note that this PR doesn't actually use `:vis`, it duplicates the code for the different varieties. the code could be reduced considerably by using the now-stabilized `:vis` macro ident type.

**Pull request merged**
