### PR TITLE
Fix indexing of &str containing Unicode.

### LINKED ISSUE #369: `tag_s!` panics when parsing Unicode `&str`
```rust
#[macro_use]
extern crate nom;

fn main() {
    named!(dot(&str) -> &str,
        tag_s!(".")
    );
    dot("點");
}
```

The above code yields the following error:

```
Yung-Hueis-MBP:osz_parse andyshiue$ RUST_BACKTRACE=1 cargo run
   Compiling osz_parse v0.0.0 (file:///Users/andyshiue/Desktop/osz_parse)
    Finished debug [unoptimized + debuginfo] target(s) in 0.32 secs
     Running `target/debug/osz_parse`
thread 'main' panicked at 'index 0 and/or 1 in `點` do not lie on character boundary', ../src/libcore/str/mod.rs:1721
stack backtrace:
   1:        0x109eec3d8 - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:        0x109eede8f - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:        0x109eed425 - std::panicking::default_hook::h0ac3811ec7cee78c
   4:        0x109eed976 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:        0x109eed814 - std::panicking::begin_panic::h6ed03353807cf54d
   6:        0x109eed732 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:        0x109eed697 - rust_begin_unwind
   8:        0x109f12b90 - core::panicking::panic_fmt::h27224b181f9f037f
   9:        0x109f130c0 - core::str::slice_error_fail::h3b64334b3fabf062
  10:        0x109ee7554 - core::str::traits::<impl core::ops::Index<core::ops::RangeTo<usize>> for str>::index::h93d6b3a34b82fcd2
  11:        0x109ee7a4e - osz_parse::main::dot::hff0fd767b1853439
  12:        0x109ee795e - osz_parse::main::h9811fbed03ff9e54
  13:        0x109eee44a - __rust_maybe_catch_panic
  14:        0x109eecf66 - std::rt::lang_start::h538f8960e7644c80
  15:        0x109ee7cd9 - main
```

### PR DESCRIPTION
**Pull request by AndyShiue**
Fix #369.

### CODE REVIEW

**Comment by AndyShiue** [comment]
I believe the usage of `unsafe` is safe here, isn't it?

**Comment by Geal** [comment]
I don't think that's the correct way (but there's indeed a bug). Ideally, I'd like to compare char by char here instead of byte by byte. From the documentation, the arguments of `slice_unchecked` must be on UTF-8 char boundaries. Why is it working while the usual slicing does not?

**Comment by AndyShiue** [comment]
The normal slicing would panic if it isn't on char boundaries. `slice_unchecked` is unsafe, but as long as the `t` is a valid `&str`,  `reduced != b` would always be true, thus it would be an error.

**Comment by Geal** [comment]
please open another pull request if you have unrelated fixes. Why would you add an empty `Display` implementation just to get a `std::error::Error` implementation for a type that is not meant to be exposed? The content of `ErrorKind` is meaningful to the developer, not to the user of your application.

**Comment by AndyShiue** [comment]
Sorry, I'm not familiar with Github and thought that commit wouldn't affect the PR. How do I reverse it?

**Comment by Geal** [comment]
no worries. The process might be a bit involved:

- first, create a new branch locally and checkout to that branch. Since your first PR comes from the master branch, create it like this: `git branch implement-error 3b8d0b74`
- do a `git cherry-pick 9868608` to get that commit from master
- push that branch to github with `git push -u origin implement-error` and create the new pull request
- checkout to master and do a `git reset --hard HEAD` to remove the last commit
- then do a `git push -f` to remove it from the pull request

**Comment by AndyShiue** [comment]
I messed up again xD

**Comment by AndyShiue** [comment]
Done

**Comment by AndyShiue** [comment]
> please open another pull request if you have unrelated fixes. Why would you add an empty `Display` implementation just to get a `std::error::Error` implementation for a type that is not meant to be exposed? The content of `ErrorKind` is meaningful to the developer, not to the user of your application.

I guess simply unwrapping the `IError` is the canonical way to do it? Coming from Haskell, I'm pretty uncomfortable about unwrapping ...

**Comment by Geal** [comment]
fixed in 28414ed

**Comment by Geal** [comment]
Hey, I'd still like to add the `std::error::Error` implementation, since people apparently relied on the older error type to implement it, but I can't find your commit. Is it ok if I mention you as the source in the commit message?

**Comment by AndyShiue** [comment]
I can't find that commit, either, haha ... just mention me in the commit message.

**Comment by Geal** [comment]
ok, here it is 5539bd2 :)

**Pull request closed without merging**
