### PR TITLE
Refactoring multi combinators

### PR DESCRIPTION
**Pull request by loewenheim**
I’ve started refactoring some functions as detailed in issue #897. With `fold_many1` I’m running into a problem: when I adapt the `fold_many1!` macro as in the latest commit, `cargo test` gives this error message:
```
error[E0282]: type annotations needed
    --> src/multi/macros.rs:550:22
     |
550  |     fold_many1!($i, |i| $submac!(i, $($args)*), $init, $fold_f)
     |                      ^ consider giving this closure parameter a type
...
1078 |     named!(multi<&[u8],Vec<&[u8]> >, fold_many1!(tag!("abcd"), Vec::new(), fold_into_vec));
     |     --------------------------------------------------------------------------------------- in this macro invocation
     |
     = note: type must be known at this point
```

When I switch the first and second rules of the macro around, I get a different (and, to me, totally incomprehensible) error:

```
error: unexpected end of macro invocation
    --> src/multi/macros.rs:1078:61
     |
607  | /   macro_rules! tag (
608  | |     ($i:expr, $inp: expr) => (
609  | |       {
610  | |         #[inline(always)]
...    |
620  | |     );
621  | |   );
     | |____- when calling this macro
...
1078 |       named!(multi<&[u8],Vec<&[u8]> >, fold_many1!(tag!("abcd"), Vec::new(), fold_into_vec));
     |                                                               ^ missing tokens in macro arguments
```

What can I do to fix this?

### CODE REVIEW

**Comment by Geal** [comment]
I think you'll have to write a `fold_many0c` variant that directly calls the closure, like it is done in `many0`. I want to only have the combinators returning closure, but to integrate them in some macros, apparently it's necessary to have the other version, so I added them, but with `#[doc(hidden)]`

**Comment by loewenheim** [comment]
Ok, I’ll do that :)

Would it also make sense to have each of the macro rules for `fold_many0!` refer directly to the function instead of another macro rule?

**Comment by loewenheim** [comment]
Something that just occurred to me: should the tests be moved from the macros to the functions?

**Comment by Geal** [comment]
the macro rules can all directly refer to the function, that can work.
The tests can stay with the macros for now.

Could you rebase this PR on master? I merged the 5.0 branch into master, and made some changes in `src/multi/mod.rs`. Also now the CI is fixed and much faster because I removed the `verbose-errors` feature :)

**Comment by loewenheim** [comment]
I wanted to implement the `many*` combinators in terms of the `fold_many*` ones, as they’re really just a special case and it cuts down on code duplication. There is a problem with that, however: we require the initial value of the fold combinators to be `Clone`. The initial value for the `many` combinators is an empty `Vec<O>`, which is only `Clone` if `O` is. Do you see a way around this?

**Comment by Geal** [comment]
I don't see another way, I guess code duplication will be ok for now

**Comment by Geal** [comment]
this is now merged into master, thanks!

**Pull request closed without merging**
