### PR TITLE
Added be_u24 method

### PR DESCRIPTION
**Pull request by valarauca**
In TLS1.0+ there are payload fields who's length is set via a 24bit unsigned integer value.

Kind of a strange method I agree. I'm not sure if you prefer `usize` or `u32`

### CODE REVIEW

**Comment by Geal** [comment]
u32 should be fine. Can you add the little endian method as well?

**Comment by valarauca** [comment]
Where should I commit the tests btw?

**Comment by Geal** [comment]
the tests should be in the same file with the others: https://github.com/Geal/nom/blob/master/src/nom.rs#L871-L956

**Comment by Geal** [comment]
ping :)

**Comment by valarauca** [comment]
Hey sorry in the middle of a move for work. I'll follow up on this when I
get the chance

**Comment by Geal** [comment]
Thanks!

**Pull request merged**
