### PR TITLE
Fix a lot of clippy warnings

### PR DESCRIPTION
**Pull request by kpp**
```
warning: using `clone` on a `Copy` type
   --> src/traits.rs:161:37
    |
161 |     fn as_char(self)      -> char { self.clone() }
    |                                     ^^^^^^^^^^^^ help: try dereferencing it: `*self`
    |
    = note: #[warn(clone_on_copy)] on by default
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.174/index.html#clone_on_copy
```

```
warning: transmute from a `u64` to a `f64`
   --> src/nom.rs:554:16
    |
554 |         Ok((i, transmute::<u64, f64>(o)))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using: `f64::from_bits(o)`
    |
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.174/index.html#transmute_int_to_float
```

```
warning: `if _ { .. } else { .. }` is an expression
   --> src/nom.rs:596:7
    |
596 | /       let mut parsed    = o;
597 | |       if o.len() > 8 {
598 | |         remaining = &input[8..];
599 | |         parsed    = &input[..8];
600 | |       }
    | |_______^ help: it is more idiomatic to write: `let <mut> parsed = if o.len() > 8 { ..; &input[..8] } else { o };`
    |
    = note: #[warn(useless_let_if_seq)] on by default
    = note: you might not need `mut` at all
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.174/index.html#useless_let_if_seq
```

```
warning: this lifetime isn't used in the function definition
   --> src/whitespace.rs:832:11
    |
832 | pub fn sp<'a,T>(input:T) -> IResult<T, T> where
    |           ^^
    |
    = note: #[warn(unused_lifetimes)] on by default
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.174/index.html#unused_lifetimes
```

```
warning: explicit lifetimes given in parameter types where they could be elided
    --> src/macros.rs:150:9
     |
150  | /         pub fn $name<'a>( i: &'a [u8] ) -> $crate::IResult<&'a [u8], $o, u32> {
151  | |             $submac!(i, $($args)*)
152  | |         }
     | |_________^
```

```
warning: casting u8 to u64 may become silently lossy if types change
   --> src/nom.rs:465:78
    |
465 |       ((i[3] as u64) << 24) + ((i[2] as u64) << 16) + ((i[1] as u64) << 8) + i[0] as u64;
    |                                                                              ^^^^^^^^^^^ help: try: `u64::from(i[0])`
    |
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.174/index.html#cast_lossless
```

```
warning: casting character literal to u8. `char`s are 4 bytes wide in rust, so casting to u8 truncates them
   --> src/nom.rs:148:30
    |
148 |   chr == ' ' as u8 || chr == '\t' as u8
    |                              ^^^^^^^^^^
    |
    = help: Consider using a byte literal instead:
            b'\t'
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.174/index.html#char_lit_as_u8
```

```
warning: this expression borrows a reference that is immediately dereferenced by the compiler
   --> src/util.rs:322:33
    |
322 |     if let Some(&s) = names.get(&code) {
    |                                 ^^^^^ help: change this to: `code`
    |
    = note: #[warn(needless_borrow)] on by default
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.174/index.html#needless_borrow
```

```
warning: this argument is passed by value, but not consumed in the function body
   --> src/util.rs:319:28
    |
319 | pub fn print_codes(colors: HashMap<u32, u8>, names: &HashMap<u32, &str>) -> String {
    |                            ^^^^^^^^^^^^^^^^ help: consider taking a reference instead: `&HashMap<u32, u8>`
    |
    = note: #[warn(needless_pass_by_value)] on by default
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.174/index.html#needless_pass_by_value
```

```
warning: returning the result of a let binding from a block. Consider returning the expression directly.
  --> src/traits.rs:50:5
   |
50 |     res
   |     ^^^
   |
   = note: #[warn(let_and_return)] on by default
note: this expression can be directly returned
  --> src/traits.rs:48:15
   |
48 |     let res = self.0.len() * 8 - self.1;
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.174/index.html#let_and_return
```

```
warning: needlessly taken reference of left operand
   --> src/bits.rs:454:20
    |
454 |           FakeUint(&self.0 << shift)
    |                    -------^^^^^^^^^
    |                    |
    |                    help: use the left value directly: `self.0`
    |
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.174/index.html#op_ref
```

```
warning: the variable `count` is used as a loop counter. Consider using `for (count, item) in $i.char_indices().enumerate()` or similar iterators
   --> src/methods.rs:317:11
    |
317 | /           for (o, _) in $i.char_indices() {
318 | |             if count == cnt {
319 | |               offset = o;
320 | |               break;
321 | |             }
322 | |             count += 1;
323 | |           }
    | |___________^
```

### CODE REVIEW

**Comment by Geal** [comment]
Hello,
Thanks for your help on this. I cherry picked most of the commits, except those ones:
- 2d347c6 "Fix casting u8 to u64 may become silently lossy if types change": I'm not sure this one will result in better code, I'll have to check later
- ccf81de "Fix unused std::result::Result which must be used": this one was already fixed
- 
4fec51c "Fix the variable `count` is used as a loop counter": not sure it will result in better code either
- d2bc566 "Fix redundant closure": what's the effect of introducing a `cloned()` call here?

**Comment by kpp** [comment]
Thanks! That's why I splitted the code into commits. 

At least `take` must be implemented using `take_split`:
```
+    fn take(&self, count: usize) -> Option<Self> {
+        match self.take_split(count) {
+            Some((_, heads)) => Some(heads),
+            None => None
+        }
+    }
```

Please notice, that you may enable clippy only if all of it's warnings will be fixed. Otherwise there would be a lot of annoying and false-positive warnings so nobody will read that 200+ messages to find a real bug.

**Comment by kpp** [comment]
d2bc566 "Fix redundant closure": Previously I already fixed a warning for redundant closure https://github.com/Geal/nom/pull/615 , this one could be fixed too, but
```
error[E0277]: the trait bound `P: std::ops::FnMut<(&u8,)>` is not satisfied
   --> src/traits.rs:224:19
    |
224 |       self.iter().position(predicate)
    |                   ^^^^^^^^ the trait `std::ops::FnMut<(&u8,)>` is not implemented for `P`
    |
    = help: consider adding a `where P: std::ops::FnMut<(&u8,)>` bound
```

That is why `.cloned()` is needed here.

**Comment by Geal** [comment]
Making nom easier to check with clippy is a good goal, but I'm against implementing all of the linter recommendations without checking their effect. Especially when it affects nom's primitive parsers, where a slight performance change can greatly affect larger parsers. So let's fix stuff, but slowly and carefully :)

**Pull request closed without merging**
