### PR TITLE
Make char! more general to accept &str.

### LINKED ISSUE #353: char! does not support &str

### PR DESCRIPTION
**Pull request by DarkDrek**
Fixes #353

### CODE REVIEW

**Comment by Geal** [comment]
I avoided doing that change before because doing a comparison with only the first byte is wrong for chars in a &str. char and the other char-related combinators (one_of, etc) only really work on bytes right now.

**Comment by ArtemGr** [comment]
> I avoided doing that change before because doing a comparison with only the first byte is wrong for chars in a &str.

Comparing with [Chars::next](https://doc.rust-lang.org/nightly/std/str/struct.Chars.html#next.v) should be okay though, shouldn't it?

**Comment by Geal** [comment]
yes, it should

**Comment by Geal** [comment]
this was fixed in a later refactoring. Thanks for the help, though!

**Pull request closed without merging**
