### PR TITLE
Add an `eof` function

### PR DESCRIPTION
**Pull request by shnewto**
The changes in this PR set out to address issue #1061, and adds a function alternative to the `eof!` macro (as well as tests for that function).

Hopefully this addition will help people who relied on `eof!` transition away from their macros and away from writing their own special case eof.

I am certainly happy to make revisions to these changes, address things you spot that I've missed, and really, would welcome any feedback, if there is some.

Thanks for taking a look! :smile:

### CODE REVIEW

**Comment by shnewto** [comment]
Haha, idk why coverage went down because in the file I touched, coverage went up 🙃 

image

If you'd like me to fill in some coverage gaps so this PR doesn't decrease coverage I'd be willing, though that seems more appropriate as separate PR

**Comment by Lucretiel** [comment]
You should make it clear that this does not work on streaming input

**Comment by shnewto** [comment]
@Lucretiel you'll have to pardon me if I'm being naive here :sweat_smile: but I don't know how `eof` would even work w/o complete data, either you're at eof or you're not right? It seems like the convention atm is to put functions that _can_ be either streaming or compete in either `src/bytes/complete.rs`, `src/character/complete.rs`, `src/bytes/streaming.rs`, or `src/character/streaming.rs`. Otherwise they live elsewhere... At least, the only places I've noticed any explicit mentions of whether the function is for streaming v complete data lives in those places. 

If I'm totally off base, I'd love it if you were willing to elaborate :smile:

**Comment by g-plane** [comment]
Are there any updates on this?

**Comment by calebsander** [comment]
Do you have an example of a use case for `eof()` that wouldn't make more sense to implement using `all_consuming()`? It seems like you can always replace `eof()` with `all_consuming(rest)` anyways.

**Comment by shnewto** [comment]
@calebsander for me in particular,`eof` is just one of the possible delimiters for the patterns I'm parsing for. And in those cases, I don't actually want to consume it if it's there (so I use `peek`).

**Comment by Geal** [comment]
Thanks!

**Pull request merged**
