### PR TITLE
Typofix - dead link - fixes #1461

### LINKED ISSUE #1461: Broken link in the README
The [HTTP Proxy](https://github.com/sozu-proxy/sozu/blob/main/lib/src/protocol/http/parser.rs) link mentioned in the README file is broken

It should be replaced by some file here: https://github.com/sozu-proxy/sozu/tree/main/lib/src/protocol/http/parser

### PR DESCRIPTION
**Pull request by SphinxKnight**
fixes #1461
I was just browsing out of curiosity and this link failed due to an apparent refactoring.
Let me know if something else is needed here :)

## Prerequisites
Issue ref: https://github.com/Geal/nom/issues/1461 (which I discovered afterwards ^^ )

### CODE REVIEW

**Comment by SphinxKnight** [comment]
@Xiretza sorry for that, I'm always confused between title and desc :x

**Comment by Xiretza** [comment]
No problem! There are two more links pointing to that repo (just grep for "sozu-proxy"), could you fix those as well while you're at it?

**Comment by SphinxKnight** [comment]
Yes, I'll fetch that locally in a few hours and'll update the PR. Thanks!

**Comment by Geal** [comment]
Thanks!

**Pull request merged**
