### PR TITLE
consumed (previously with_input) parser combinator

### PR DESCRIPTION
**Pull request by Alfriadox**
This replaces #1127 

This pull request adds a new parser combinator, similar to recognize. This combinator, called "consumed," returns the consumed input along with the parser result. 

TODO:
- [x] Implement combinator
- [x] Write documentation
- [x] Modify [combinator list](https://github.com/Geal/nom/blob/master/doc/choosing_a_combinator.md)
- [ ] Macro version.

Comments and feedback appreciated!

### CODE REVIEW

**Comment by Alfriadox** [comment]
@Geal I cannot create a proper macro version of this combinator similar to the one for `recognize!` because the output type conflicts with the one specified in `named!`. Otherwise this PR should be ready for merge. What are your thoughts?

**Comment by Stargateur** [comment]
I'm not a native English speaker. `consumed` is not very self describing in my opinion.

**Comment by Alfriadox** [comment]
@Stargateur That's understandable! What would you suggest as a name -- I don't want to make it too verbose.

**Comment by Alfriadox** [comment]
When this PR is merged I think it should close #1183. I don't have the permissions to link the issue right now though I think.

**Comment by Geal** [comment]
thank you for this new combinator!  Don't worry about the macro version, they're not used as much these days

**Pull request merged**
