### PR TITLE
chain2 and nested_chain test addition

### PR DESCRIPTION
**Pull request by tstorch**
chain2 and nested_chain test addition

### CODE REVIEW

**Comment by tstorch** [comment]
This is the last PR that was in #184 . The other changes were mere renamings

**Comment by tstorch** [comment]
Reordered stuff like in #208 and #209, which you accepted. Should everything be like this?

**Comment by Geal** [comment]
I accepted #208 and #209 because I felt they did not reduce too much readability, but as I said in #204, I prefer when everything is on the same line, or two close lines, like this:

```rust
let r1 = f(&b"abcdabcdefghefghX"[..]);
assert_eq!(r1, Done(&b"X"[..], B{a: 1, b: 2}));

let r2 = f(&b"abcdefghefghX"[..]);
assert_eq!(r2, Done(&b"X"[..], B{a: 1, b: 2}));
```

or like this:

```rust
assert_eq!( f(&b"abcdabcdefghefghX"[..]), Done(&b"X"[..], B{a: 1, b: 2}));
assert_eq!(f(&b"abcdefghefghX"[..]), Done(&b"X"[..], B{a: 1, b: 2}));
```
This is really a matter of taste, but since I'll have to maintain it, I'd rather have everything fit the style I'm used to.

**Comment by tstorch** [comment]
So I revert/delete the last commit here?

**Comment by Geal** [comment]
yes, please do

**Comment by tstorch** [comment]
Done

**Comment by tstorch** [comment]
Ok. Now every PR, involving tests got reordered and partially rebased to the new master. Now everything should be fine.

**Comment by Geal** [comment]
Thanks

**Pull request merged**
