### PR TITLE
Missing imports while testing

### PR DESCRIPTION
**Pull request by kamarkiewicz**
Fix missing imports for `cargo test --no-default-features` on latest nightly.

### CODE REVIEW

**Comment by kamarkiewicz** [comment]
This is how it looks like on master in CI after #634 
https://travis-ci.org/kamarkiewicz/nom/builds/311958846

**Comment by Geal** [comment]
oh, I should really read all PRs before merging :/
Thanks!

**Comment by kamarkiewicz** [comment]
@Geal its OK, I really appreciate your work here. Please, just don't forget to remove the line:
`script: cargo build --verbose --no-default-features`
as `no_std` on nightly should be tested, 'cause I care about this feature.

**Comment by Geal** [comment]
remove it, or put it again with the others with `cargo test`?

**Comment by Geal** [comment]
oh, right, I see what you mean

**Comment by kamarkiewicz** [comment]
Thank you for https://github.com/Geal/nom/commit/ea622a9710b521d498a82b1876997e150bec4de2 :)

**Comment by Geal** [comment]
I honestly didn't think the tests would ever pass in no_std, thank you again for helping on this :)

**Pull request merged**
