### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by nickelc**
clippy::unnecessary_cast

### CODE REVIEW

**Comment by Stargateur** [comment]
why not `0u8` ?

**Comment by nickelc** [comment]
clippy suggests it like this for some time now

```
warning: casting integer literal to `u8` is unnecessary
 --> src/main.rs:3:13
  |
3 |     let a = 0 as u8;
  |             ^^^^^^^ help: try: `0_u8`
  |
  = note: `#[warn(clippy::unnecessary_cast)]` on by default

**Comment by Stargateur** [comment]
I never see such convention, I'm not opposite but I found it strange that clippy advice it, I never see any discussion about that, rustfmt doesn't fmt it like that neither. I think I will open an issue on clippy to ask about that.

The warning is also quite very pedantic, main purpose is to reduce character number... so add an underscore to "be clear" is opposite to the main goal. So I think `0u8` make more sense.

**Comment by Geal** [comment]
thanks. I don't really care much about `0u8` vs `0_u8` to be honest

**Pull request merged**
